execution_mode: random
# repeat: true
scenarios:
  # - name: "chrome_scenario"
  #   method: "browse"
  #   delay: 2
  #   args: ["www.python.org"]
  # - name: "word_scenario"
  #   method: "write"
  #   delay: 2
  #   args: ["haloooo, tes satu dua tiga!"]
  # - name: "firefox_scenario"
  #   method: "browse"
  #   delay: 2
  #   args: ["www.python.org"]
  # - name: "google_form_scenario"
  #   browser: "firefox_scenario"
  #   method: "fill"
  #   args: ["https://forms.gle/1wCpoSWBjQqVvtVv5", ["short answer", "lorem ipsum", "paragraph answer"]]
  - name: "google_form_scenario"
    browser: "firefox_scenario"
    method: "create"
    args:
      - "Form Testing"
      - "form ini digunakan untuk testing"
      - 
        - ["Short answer", "question 1", True]
        - ["Paragraph", "question 2", True]
        - ["Short answer", "question 3", False]