execution_mode: "random"
# repeat: "true"
scenario:
  - name: "Microsoft Paint"
    methods:
      - method: "create_window"
        delay: 2
      - method: "draw"
        delay: 2
        args: 
          points: 
            - [1110, 625]
            - [1102, 675]
            - [1079, 721]
            - [1043, 760]
            - [997, 787]
            - [945, 798]
            - [892, 793]
            - [844, 770]
            - [808, 735]
            - [787, 690]
            - [780, 640]
            - [788, 590]
            - [811, 544]
            - [847, 505]
            - [893, 478]
            - [945, 467]
            - [998, 472]
            - [1046, 495]
            - [1082, 530]
            - [1103, 575]
            - [1110, 625]
          speed: 1
      - method: "change_thickness"
        delay: 2
        args:
          direction: "up"
          count: 10
      - method: "draw_random"
        delay: 2
        args:
          count: 30
          speed: 1
  # - name: "Microsoft Excel"
  #   methods:
  #   - method: "create_window"
  #     delay: 2
  #   - method: "open_xlsx"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Downloads\\dummy.xlsx"
  #   - method: "change_cell"
  #     delay: 2
  #     args:
  #       target_cell: "F5"
  #   - method: "create_sheet"
  #     delay: 2
  #   - method: "rename_sheet"
  #     delay: 2
  #     args:
  #       new_name: "Dummy"
  #   - method: "create_sheet"
  #     delay: 2
  #   - method: "rename_sheet"
  #     delay: 2
  #     args:
  #       new_name: "Test"
  #   - method: "change_sheet"
  #     delay: 2
  #     args:
  #       direction: "right"
  #       count: 2
  #   - method: "change_sheet"
  #     delay: 2
  #     args:
  #       direction: "left"
  #       count: 1
  #   - method: "write_cell"
  #     delay: 2
  #     args:
  #       text: "haloooo, tes satu dua tiga!"
  #   - method: "scroll"
  #     delay: 2
  #     args:
  #       direction: "down"
  #       clicks: 30
  #       scroll_delay: 0.05
  #   - method: "save_xlsx"
  #     delay: 2
  # - name: "Selenium Script"
  #   methods:
  #     - method: "run_pytest"
  #       delay: 2
  #       args:
  #         path: "C:\\Users\\ASUS\\Documents\\Kuliah\\SEM 8\\TA\\user-activity-simulation\\testcase1.py"
  # - name: "AutoIt Function"
  #   methods:
  #     - method: "mouse_move"
  #       delay: 2
  #       args:
  #         x: 768
  #         y: 432
  #         speed: 10
  #     - method: "mouse_move"
  #       delay: 2
  #       args:
  #         x: 960
  #         y: 540
  #         speed: 10
  #   - method: "run"
  #     delay: 2
  #     args:
  #       exe_path: 'C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE "C:\\Users\\ASUS\\Downloads\\dummy.docx"'
  #       working_dir: ""
  #       flag: 1
  # - name: "Notepad"
  #   methods:
  #   - method: "create_window"
  #     delay: 2
  #   - method: "open_file"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Downloads\\credentials.json"
  #   - method: "write_file"
  #     delay: 2
  #     args:
  #       text: "test write file"
  #   - method: "scroll"
  #     delay: 2
  #     args:
  #       direction: "up"
  #       clicks: 30
  #       scroll_delay: 0.05
  #   - method: "save_file"
  #     delay: 2
  # - name: "File Explorer"
  #   methods:
  #   - method: "create_window"
  #     delay: 2
  #   - method: "open_file"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Downloads\\dummy.docx"
  #   - method: "change_directory"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Documents"
  #   - method: "create_directory"
  #     delay: 2
  #     args:
  #       parent_path: "C:\\Users\\ASUS\\Downloads"
  #       dir_name: "testtt"
  # - name: "Command Prompt"
  #   methods:
  #   - method: "create_window"
  #     delay: 2
  #   - method: "open_file"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Downloads\\t.sql"
  #   - method: "change_directory"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Documents\\Kuliah\\SEM 8"
  #   - method: "create_directory"
  #     delay: 2
  #     args:
  #       parent_path: "C:\\Users\\ASUS\\Downloads"
  #       dir_name: "dummyyy"
  # - name: "Google Chrome"
  #   methods:
  #     - method: "create_window"
  #       delay: 2
  #     - method: "zoom_in"
  #       delay: 2
  #       args:
  #         count: 10
  #     - method: "zoom_out"
  #       delay: 2
  #       args:
  #         count: 12
  #   - method: "create_tab"
  #     delay: 2
  #   - method: "browse"
  #     delay: 2
  #     args:
  #       url: "www.python.org"
  #   - method: "scroll"
  #     delay: 2
  #     args:
  #       direction: "down"
  #       clicks: 30
  #       scroll_delay: 0.03
  # - name: "Mozilla Firefox"
  #   methods:
  #   - method: "create_window"
  #     delay: 2
  #   - method: "create_tab"
  #     delay: 2
  #   - method: "browse"
  #     delay: 2
  #     args:
  #       url: "www.python.org"
  #   - method: "scroll"
  #     delay: 0.5
  #     args:
  #       direction: "down"
  #       clicks: 30
  #       scroll_delay: 0.07
  #   - method: "scroll"
  #     delay: 2
  #     args:
  #       direction: "up"
  #       clicks: 15
  #       scroll_delay: 0.05
  # - name: "Microsoft Word"
  #   methods:
  #   - method: "create_window"
  #     delay: 2
  #   - method: "open_docx"
  #     delay: 2
  #     args:
  #       path: "C:\\Users\\ASUS\\Downloads\\dummy.docx"
  #   - method: "write_docx"
  #     delay: 2
  #     args:
  #       text: "haloooo, tes satu dua tiga!"
  #   - method: "scroll"
  #     delay: 2
  #     args:
  #       direction: "up"
  #       clicks: 30
  #       scroll_delay: 0.05
  #   - method: "save_docx"
  #     delay: 2
  # - name: "Google Forms"
  #   browser: "Mozilla Firefox"
  #   methods:
  #   - method: "fill_form"
  #     delay: 2
  #     args:
  #       url: "https://forms.gle/1wCpoSWBjQqVvtVv5"
  #       answers: ["short answer", "lorem ipsum", "paragraph answer"]
  # - name: "Google Forms"
  #   browser: "Mozilla Firefox"
  #   methods:
  #   - method: "create_form"
  #     delay: 2
  #     args:
  #       title: "Form Testing"
  #       description: "form ini digunakan untuk testing"
  #       questions:
  #         - ["Short answer", "question 1", true]
  #         - ["Paragraph", "question 2", true]
  #         - ["Short answer", "question 3", false]